[tool.pysen]
version = "0.10"

[tool.pysen.lint]
enable_black = true
enable_flake8 = false
enable_isort = true
enable_mypy = false
mypy_preset = "strict"
line_length = 79
py_version = "py37"
[[tool.pysen.lint.mypy_targets]]
  paths = ["."]
